### ISSUE TITLE
launch stalls  with 'Valid api_|id must be provided

### ISSUE THREAD

**Issue by plum** [TruncatedDinosour/arigram#19]
Ho, looks really good, but this error occurs,  implyiing app_id authentication.

`raise RuntimeError(f'Telegram error: {self.error_info}')
RuntimeError: Telegram error: {'@type': 'error', 'code': 400, 'message': 'Valid api_id must be provided. Can be obtained at https://my.telegram.org', '@extra': {'request_id': 'updateAuthorizationState'}}`

Arigram was installed  from aur  community package ,  V. 0.1.6-1

I dont have an app_id myself  , although i have a telegram account of course.  I had expected the ap_id would be registered somehwhere  in the  installe d package.

My telephone number, as entered on the command after arigram, has been recorded in the arigram/config.py

Any help, appreciated.
John

**Comment by ar1ja** [comment]
im sorry to hear that

to clearify, i half abandoned this project and i barely work on it
anymore these days and i dont maintain the aur package so i dont know whats going on

the app_id is already pre-packaged into the client https://github.com/TruncatedDinosour/arigram/blob/main/arigram/config.py#L25..L26 so im very confused why such error would happen, maybe you overwrote it somehow, maybe even in config.py ?

maybe some other arigram users know, but i even now currently have arigram open and its fine,
very concerned why its broken for you :/ if anything lmk :)

**Comment by ghost** [comment]
I have this error. Changed `API_ID` and `API_HASH` to mine, recompiled. Same error. Probably, something changed in telegram api idk. Not a python dev so can't really check

**Comment by ar1ja** [comment]
> I have this error. Changed `API_ID` and `API_HASH` to mine, recompiled. Same error. Probably, something changed in telegram api idk. Not a python dev so can't really check

thats odd, weirdly still works for me and i doubt its anything with the api as i try to keep up with the changes, if it was gonna happen itd happen to me too

**Comment by ar1ja** [comment]
maybe the AUR package is broken or something ? i dont maintain it though

**Comment by ghost** [comment]
I installed from sources.

My OS:
```
Distributor ID:	Elementary
Description:	elementary OS 6.1 Jólnir
Release:	6.1
Codename:	jolnir
```

**Comment by ar1ja** [comment]
> I installed from sources.
> 
> My OS:
> 
> ```
> Distributor ID:	Elementary
> Description:	elementary OS 6.1 Jólnir
> Release:	6.1
> Codename:	jolnir
> ```

maybe this fixes it ? i bumped the python tg version
https://github.com/TruncatedDinosour/arigram/releases/tag/v0.1.7

**Comment by ghost** [comment]
> > I installed from sources.
> > 
> > My OS:
> > 
> > ```
> > Distributor ID:	Elementary
> > Description:	elementary OS 6.1 Jólnir
> > Release:	6.1
> > Codename:	jolnir
> > ```
> 
> maybe this fixes it ? i bumped the python tg version
> https://github.com/TruncatedDinosour/arigram/releases/tag/v0.1.7

I'll try in a moment. Will notify

**Comment by ar1ja** [comment]
just in case, ill leave the house for now as i got plans with my best friend, ill be back in a couple of hours, sorry for the delay in responses in advance, id give 24/7 support if i could, but im just a teenage developer, not a large tech company <33

**Comment by ghost** [comment]
dude, relax, you don't owe me or anybody else anything.
have a great one 🫡

**Comment by ghost** [comment]
unfortunately, error persists

![Screenshot from 2023-03-06 16-41-43](https://user-images.githubusercontent.com/66746788/223143375-3f05101b-3b1c-4999-b0c9-3ef62dc2a589.png)
![Screenshot from 2023-03-06 16-42-04](https://user-images.githubusercontent.com/66746788/223143412-04249209-c094-4421-b944-4f1f0f86fff8.png)

**Comment by ghost** [comment]
tried creating fresh user on system - same

**Comment by ar1ja** [comment]
> unfortunately, error persists
> 
> ![Screenshot from 2023-03-06 16-41-43](https://user-images.githubusercontent.com/66746788/223143375-3f05101b-3b1c-4999-b0c9-3ef62dc2a589.png) ![Screenshot from 2023-03-06 16-42-04](https://user-images.githubusercontent.com/66746788/223143412-04249209-c094-4421-b944-4f1f0f86fff8.png)

this is so odd, ill try and research it

**Comment by ar1ja** [comment]
![mpv-shot0002](https://user-images.githubusercontent.com/71613062/223167055-3720ef81-774e-4603-9c16-d0dbc98765ba.jpg)

this is with `~/.config/arigram` and `~/.cache/arigram` removed, it all works, im so lost, why am i unable to reacreate the error

**Comment by ghost** [comment]
wait, I didn't try purging cache. will be back in a sec

**Comment by ghost** [comment]
well, apparently I don't have cache for arigram

**Comment by ar1ja** [comment]
> well, apparently I don't have cache for arigram

i guess its because you havent even been able to log in

**Comment by ghost** [comment]
I will try installing arigram on virtual machine. Hope it'll work

**Comment by ar1ja** [comment]
its still very suspicious that it even breaks on 2 systems

**Comment by ar1ja** [comment]
> I will try installing arigram on virtual machine. Hope it'll work

ill try it on a fresh void linux vm too

**Comment by ar1ja** [comment]
![mpv-shot0001](https://user-images.githubusercontent.com/71613062/223172142-3292df39-7a9f-460e-8f7e-cdbaf85f8b87.jpg)
this is a fully fresh void linux vm, still works, so lost still, looking up the error isnt much helpful either

**Comment by plum** [comment]
@ truncatedDinosaur
I did  grab the app ID from package files and entered them into my local conf, but the error persists.

**Comment by ar1ja** [comment]
> @ truncatedDinosaur I did grab the app ID from package files and entered them into my local conf, but the error persists.

yeah, i know, its probably not related to that, the problem in it is that i am unable to reproduce it no matter what, im unsure whats so broken that makes your arigram install scream

**Comment by bogdanbpeterson** [comment]
installed fresh ubuntu still same

![Screenshot from 2023-03-07 16-44-06](https://user-images.githubusercontent.com/118484531/223458810-7ab29991-6cbf-4fac-ad36-26df75a27ceb.png)

**Comment by ghost** [comment]
installed on fresh Ubuntu 22.04. Had an issue with libssl.so.1.1
![Screenshot from 2023-03-07 16-44-06](https://user-images.githubusercontent.com/118484531/223464052-a54bbd3c-8fac-4da6-a9ca-7f218a644b82.png)
resolved thanks to https://stackoverflow.com/a/73604364

**Comment by ghost** [comment]
but now `arigram` works just fine

**Comment by ar1ja** [comment]
> but now `arigram` works just fine

hm, but now why is it broken for you two

**Comment by plum** [comment]
@bogdan:
OK, that's useful  I'll check out the lib.ssl.so issue  in some way or another.
I  dimly recall I have had issues with libssl.so  in the past with  some other applications, and managed to resolve it, but without a fresh install of my system.

**Comment by ar1ja** [comment]
> @bogdan: OK, that's useful I'll check out the lib.ssl.so issue in some way or another. I dimly recall I have had issues with libssl.so in the past with some other applications, and managed to resolve it, but without a fresh install of my system.

so, any update ?

**Comment by r-scheffler** [comment]
hey, got the same issue after a fresh arch install.

**Comment by ar1ja** [comment]
> hey, got the same issue after a fresh arch install.

hihi, we still dont know what the cause is, if you figure it out, please tell us <3

**Comment by plum** [comment]
On arch I see there are two lib32-openssl  packages: perhaps that is the cause of the problem

_$ pacman -Ss openssl_ 
```

multilib/lib32-openssl 1:3.0.8-1 [installed]
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security (32-bit)
multilib/lib32-openssl-1.1 1.1.1.t-1
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
```

These provide the  lib.ssl.so  file.
As you can see, I'm on the later version, and  reported the  problem as an issue. I could try swapping the round and testing, OR meanwhile, you could let me know, which version you are running.

**Comment by ar1ja** [comment]
> On arch I see there are two lib32-openssl packages: perhaps that is the cause of the problem
> 
> _$ pacman -Ss openssl_
> 
> ```
> 
> multilib/lib32-openssl 1:3.0.8-1 [installed]
>     The Open Source toolkit for Secure Sockets Layer and Transport Layer Security (32-bit)
> multilib/lib32-openssl-1.1 1.1.1.t-1
>     The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
> ```
> 
> These provide the lib.ssl.so file. As you can see, I'm on the later version, and reported the problem as an issue. I could try swapping the round and testing, OR meanwhile, you could let me know, which version you are running.

i use openssl version 1.1.1, gentoos latest

**Comment by ghost** [comment]
interestingly enough it works on _EndevourOS_ just fine. No `python` errors, no `openssl` errors, nothing.

**Comment by ar1ja** [comment]
> interestingly enough it works on _EndevourOS_ just fine. No `python` errors, no `openssl` errors, nothing.

yeah, its unreproducable on my gentoo, nor on a void vm, nothing, idk whats up, no clue what to fix

**Comment by plum** [comment]
Form what's been reported so far I think we can conclude the key is valid and it should be read with OK with required dependencies.  Therefore, It seems like it could be down to the aur package. It is actively maintained  and Imyself coul dnot see any obvious problems there, when taking a breif look: Here are the details;

[aur arigram.git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=arigram  :)
root/pckbuild:
```
 Maintainer: Onur BÜBER <onurbuber@engineer.com>
# Developer: Ari Archer <ari.web.xyz@gmail.com>

pkgname=arigram
pkgver=0.1.6
pkgrel=1
pkgdesc='A fork of tg -- a hackable telegram TUI client'
arch=('x86_64')
url='https://github.com/TruncatedDinosour/arigram.git'
license=('Unlicense')
provides=('arigram')
conflicts=('arigram')
optdepends=('ffmpeg'
	    	'nnn'
	    	'fzf'
	    	'ranger')
makedepends=('python'
		     'python-pip'
		     'python-telegram'
	     	 'python-pyfzf'
	     	 'python-pyperclip'
         	 'bash'
	     	 'git')
source=("$pkgname-$pkgver.tar.gz::https://github.com/TruncatedDinosour/arigram/archive/refs/tags/v$pkgver.tar.gz")
sha256sums=('f3319df1990805c977b3759a67228793dc67f78ed9c21f9098ffade0095d35f0')

build() {
    cd "$srcdir/$pkgname-$pkgver"
    python setup.py build

}

package() {
    cd "$srcdir/$pkgname-$pkgver"
    python setup.py install --root="$pkgdir"
    install -Dm644 UNLICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
```

It's pulling arigram version  0.1.6.1 

$ pacman -Qi arigram   
```
Name            : arigram
Version         : 0.1.6-1
Description     : A fork of tg -- a hackable telegram TUI client
Architecture    : x86_64
URL             : https://github.com/TruncatedDinosour/arigram.git


```
I've just now posted this issue to the package maintainer for his comments on this problem experienced by only  arch users.

**Comment by ar1ja** [comment]
im guessing the issue is solved so ill close it, thank you for active convo when needed

**Comment by Yehoward** [comment]
Not solved, yet. I have the problem both from built version and from AUR. What's even weirder is that I didn't have the problem from the start. It ran "fine", the only serious error being that I couldn't type. I solved it (in controllers.py at the line 582 changed the permission `can_send_message` to `can_send_basic_message`), and it worked fine for a bit, then it gave me a `RuntimeError: Telegram error: {'@type': 'error', 'code': 400, 'message': 'Valid api_id must be provided. Can be obtained at https://my.telegram.org', '@extra': {'request_id': 'updateAuthorizationState'}}`. I tried a different API id, and still doesn't work. 

Even though in my case it may seem as an user error, I highly doubt it.

**Comment by ar1ja** [comment]
> Not solved, yet. I have the problem both from built version and from AUR. What's even weirder is that I didn't have the problem from the start. It ran "fine", the only serious error being that I couldn't type. I solved it (in controllers.py at the line 582 changed the permission `can_send_message` to `can_send_basic_message`), and it worked fine for a bit, then it gave me a `RuntimeError: Telegram error: {'@type': 'error', 'code': 400, 'message': 'Valid api_id must be provided. Can be obtained at https://my.telegram.org', '@extra': {'request_id': 'updateAuthorizationState'}}`. I tried a different API id, and still doesn't work.
> 
> Even though in my case it may seem as an user error, I highly doubt it.

sorry, ion rlly work on this anymore, the current state of this project is 'if it works for me its good enough for everyone' and what id suggest is forking this, i am sorry for the accumulating errors and functionality loss over time, ill reopen this just in case the community wants to solve this or yall wanna advertise any forks

**Comment by Yehoward** [comment]
> > Not solved, yet. I have the problem both from built version and from AUR. What's even weirder is that I didn't have the problem from the start. It ran "fine", the only serious error being that I couldn't type. I solved it (in controllers.py at the line 582 changed the permission `can_send_message` to `can_send_basic_message`), and it worked fine for a bit, then it gave me a `RuntimeError: Telegram error: {'@type': 'error', 'code': 400, 'message': 'Valid api_id must be provided. Can be obtained at https://my.telegram.org', '@extra': {'request_id': 'updateAuthorizationState'}}`. I tried a different API id, and still doesn't work.
> > Even though in my case it may seem as an user error, I highly doubt it.
> 
> sorry, ion rlly work on this anymore, the current state of this project is 'if it works for me its good enough for everyone' and what id suggest is forking this, i am sorry for the accumulating errors and functionality loss over time, ill reopen this just in case the community wants to solve this or yall wanna advertise any forks

Yes, I understand. I'll try to fix it, and if I succeed I'll let you know.

**Comment by Yehoward** [comment]
I found the error, and it was a user one. I was using `python-telegram 0.17.0` [which doesn't support the latest version of TDLib](https://github.com/alexander-akhmetov/python-telegram/issues/348#issuecomment-1411202456). I updated python-telegram to 0.18.0 and everything works.



> What's even weirder is that I didn't have the problem from the start. It ran "fine", the only serious error being that I couldn't type.

I bet that was caused by the fact that I had two python-telegram packages installed, one from AUR with the latest version and one from pip.
You may want to change the `python-telegram` version in `pyproject.toml` to "^0.18.0".

**Comment by ar1ja** [comment]
hey, as this issue is still open i'd like to make it clear that this project has had its final release and i encourage to go find or start other arigram forks

https://github.com/TruncatedDinoSour/arigram/releases/tag/v0.1.8
https://github.com/TruncatedDinoSour/arigram/forks
https://github.com/TruncatedDinoSour/arigram/#featured-forks
